### ISSUE TITLE
Transform direct S3 URLs

### ISSUE THREAD

**Issue by adammcmaster** [zooniverse/Talk-archiver#49]
As part of migrating to Azure we'll need to move our data off of S3. Ideally we will identify any projects which use direct S3 URLs for subjects and rewrite their URLs to a domain that we control (i.e. static.zooniverse.org in most cases).

**Comment by eatyourgreens** [comment]
This is slightly complicated because subject URLs are denormalised throughout the Ouroboros API responses. Some projects also use buckets other than `zooniverse-static` eg.
http://asteroidzoo.s3.amazonaws.com/CSS/703/2012/12Jun17/azoo/01_12JUN17_N26072_0001-91-scaled.png
https://mwp-development.s3.amazonaws.com/bubble_centred/large/GLM_327144%2B00917_mosaic_0.0947x0.0473_I24M1.jpg

**Comment by eatyourgreens** [comment]
S3 URLs can also appear in OpenGraph metadata, so those URLs need to be rewritten too.
```html
<meta property='og:image' content="http://zooniverse-static.s3.amazonaws.com/www.sciencegossip.org/subjects/standard/56c48a26bcdc200042002361.jpg" />
<meta name='twitter:image' content="http://zooniverse-static.s3.amazonaws.com/www.sciencegossip.org/subjects/standard/56c48a26bcdc200042002361.jpg" />
```

**Comment by eatyourgreens** [comment]
While we're at it, HTTP URLs should be rewritten to use HTTPs.
